title: FMCS @ ICML2026
author: Â© 2026 FMCS Organizers. All rights reserved.
description: Foundation Models in Computational Science Workshop @ ICML2026
theme: minima
markdown: kramdown
baseurl: "/icml2026"
